#!/bin/bash

set -e

# Mac OS comes with zsh, so move the existing zshrc if it exists
if [ -e "$HOME/.zshrc" ] && [ ! -L "$HOME/.zshrc" ]; then
	echo ".zshrc exists and is not a symlink, moving it to .zshrc-pre-stow"
	mv "$HOME/.zshrc" "$HOME/.zshrc-pre-stow"
fi

stow_directory() {
	stow --verbose=2 --dotfiles -d "$HOME/.dotfiles" -t "$HOME" $1
}

stow_directory "asdf"
stow_directory "irb"
stow_directory "nvim"
stow_directory "script"
stow_directory "starship"
stow_directory "tmux"
stow_directory "wezterm"
stow_directory "zsh"
